version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME:?err}-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config/nginx:/etc/nginx/conf.d"
      - "./:/home/zeltlager"
    restart: 'always'
    depends_on:
      - php
      - mariadb
  php:
    build:
      dockerfile: php.Dockerfile
    container_name: ${APP_NAME:?err}-php
    volumes:
      - "./:/home/zeltlager"
      - "./config/php/php.ini:/usr/local/etc/php/php.ini"
  mariadb:
    image: mariadb:10.3.9
    container_name: ${APP_NAME:?err}-mariadb
    restart: 'on-failure'
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS:?err}
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
  composer:
    build:
      dockerfile: composer.Dockerfile
    container_name: ${APP_NAME:?err}-composer
    restart: 'on-failure'
    volumes:
      - "./:/home/zeltlager"
  phpmyadmin:
    image: phpmyadmin
    container_name: ${APP_NAME:?err}-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST:?err}
      - PMA_PORT=${DB_PORT:?err}